spring:
  application:
    name: find-my-edge

  datasource:
    url: jdbc:mysql://localhost:3306/find_my_edge
    username: root
    password: Ansh@2004

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  jackson:
    time-zone: Asia/Kolkata

    mapper:
      accept-case-insensitive-enums: true
